# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# CircleCI configuration file for iOS project
version: 2.1
jobs:
  test:
    macos:
      xcode: "15.4"  # Usa la versión de Xcode que prefieras
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            xcodebuild test \
              -workspace SmartSavingsWorkspace.xcworkspace \
              -scheme PersistenceModuleTests \
              -destination 'platform=iOS Simulator,name=iPhone 12,OS=17.4' \
              ONLY_ACTIVE_ARCH=NO

  build:
    macos:
      xcode: "15.4"  # Usa la versión de Xcode que prefieras
    steps:
      - checkout
      - run:
          name: Build the app
          command: |
            xcodebuild build \
              -workspace SmartSavingsWorkspace.xcworkspace \
              -scheme PersistenceModuleTests \
              -destination 'platform=iOS Simulator,name=iPhone 12,OS=17.4' \
              ONLY_ACTIVE_ARCH=NO

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'

workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
