# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# CircleCI configuration file for iOS project
version: 2.1

executors:
  macos-executor:
    macos:
      xcode: "15.4"

jobs:
  test:
    executor: macos-executor
    steps:
      - checkout
      - run:
          name: List available device types
          command: xcrun simctl list devicetypes

      - run:
          name: List available runtimes
          command: xcrun simctl list runtimes

      - run:
          name: Create and boot iPhone 15 simulator
          command: |
            xcrun simctl create "iPhone 15" com.apple.CoreSimulator.SimDeviceType.iPhone-15 com.apple.CoreSimulator.SimRuntime.iOS-17-5 || true
            xcrun simctl boot "iPhone 15" || true

      - run:
          name: Run tests
          command: |
            xcodebuild test \
              -workspace SmartSavingsWorkspace.xcworkspace \
              -scheme PersistenceModuleTests \
              -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
              ONLY_ACTIVE_ARCH=NO

  build:
    executor: macos-executor
    steps:
      - checkout
      - run:
          name: List available device types
          command: xcrun simctl list devicetypes

      - run:
          name: List available runtimes
          command: xcrun simctl list runtimes

      - run:
          name: Create and boot iPhone 15 simulator
          command: |
            xcrun simctl create "iPhone 15" com.apple.CoreSimulator.SimDeviceType.iPhone-15 com.apple.CoreSimulator.SimRuntime.iOS-17-5 || true
            xcrun simctl boot "iPhone 15" || true

      - run:
          name: Build the app
          command: |
            xcodebuild build \
              -workspace SmartSavingsWorkspace.xcworkspace \
              -scheme PersistenceModuleTests \
              -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
              ONLY_ACTIVE_ARCH=NO

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'

workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build

