# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# CircleCI configuration file for iOS project
version: 2.1

executors:
  macos-executor:
    macos:
      xcode: "15.4"

jobs:
  test:
    executor: macos-executor
    steps:
      - checkout
      - run:
          name: Create and boot iPhone 15 simulator
          command: |
            SIM_ID=$(xcrun simctl create "iPhone 15" com.apple.CoreSimulator.SimDeviceType.iPhone-15 com.apple.CoreSimulator.SimRuntime.iOS-17-5)
            echo "Simulator ID: $SIM_ID"
            xcrun simctl boot "$SIM_ID" || true
            echo $SIM_ID > sim_id.txt

      - run:
          name: Run tests
          command: |
            SIM_ID=$(cat sim_id.txt)
            xcodebuild test \
              -workspace SmartSavingsWorkspace.xcworkspace \
              -scheme PersistenceModuleTests \
              -destination "id=$SIM_ID" \
              ONLY_ACTIVE_ARCH=NO

      - run:
          name: Delete simulator
          command: |
            SIM_ID=$(cat sim_id.txt)
            xcrun simctl delete "$SIM_ID"

  build:
    executor: macos-executor
    steps:
      - checkout
      - run:
          name: Create and boot iPhone 15 simulator
          command: |
            SIM_ID=$(xcrun simctl create "iPhone 15" com.apple.CoreSimulator.SimDeviceType.iPhone-15 com.apple.CoreSimulator.SimRuntime.iOS-17-5)
            echo "Simulator ID: $SIM_ID"
            xcrun simctl boot "$SIM_ID" || true
            echo $SIM_ID > sim_id.txt

      - run:
          name: Build the app
          command: |
            SIM_ID=$(cat sim_id.txt)
            xcodebuild build \
              -workspace SmartSavingsWorkspace.xcworkspace \
              -scheme PersistenceModuleTests \
              -destination "id=$SIM_ID" \
              ONLY_ACTIVE_ARCH=NO

      - run:
          name: Delete simulator
          command: |
            SIM_ID=$(cat sim_id.txt)
            xcrun simctl delete "$SIM_ID"

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'

workflows:
  workflow:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build


